import Shade from './shade';

const LightColors = {
  primary: Shade.purple[4],
  onPrimary: Shade.white[0],
  secondary: Shade.rose[4],
  onSecondary: Shade.white[0],
  tertiary: Shade.gray[0],
  onTertiary: Shade.gray[0],
  background: Shade.purple[0],
  onBackground: Shade.white[0],
  surface: Shade.white[0],
  onSurface: Shade.gray[4],
  surfaceVariant: Shade.purple[0],
  onSurfaceVariant: Shade.rose[1],
  primaryContainer: Shade.blue[1],
  onPrimaryContainer: Shade.yellow[1],
  secondaryContainer: Shade.orange[1],
  onSecondaryContainer: Shade.teal[1],
  tertiaryContainer: Shade.indigo[1],
  onTertiaryContainer: Shade.cyan[1],
  errorContainer: Shade.pink[1],
  onErrorContainer: Shade.lime[1],
  inverseSurface: Shade.brown[1],
  inverseOnSurface: Shade.green[0],
  inversePrimary: Shade.red[0],
  error: Shade.red[4],
  onError: Shade.green[4],
  shadow: Shade.orange[4],
  scrim: Shade.rose[4],
  outline: Shade.gray[3],
};

const DarkColors = {
  primary: Shade.white[0],
  onPrimary: Shade.purple[4],
  secondary: Shade.white[0],
  onSecondary: Shade.gray[4],
  tertiary: Shade.gray[4],
  onTertiary: Shade.black[0],
  background: Shade.black[0],
  onBackground: Shade.white[0],
  surface: Shade.black[0],
  onSurface: Shade.white[0],
  surfaceVariant: Shade.gray[4],
  onSurfaceVariant: Shade.rose[4],
  primaryContainer: Shade.blue[4],
  onPrimaryContainer: Shade.yellow[4],
  secondaryContainer: Shade.orange[4],
  onSecondaryContainer: Shade.teal[4],
  tertiaryContainer: Shade.indigo[4],
  onTertiaryContainer: Shade.cyan[4],
  errorContainer: Shade.pink[4],
  onErrorContainer: Shade.lime[4],
  inverseSurface: Shade.brown[4],
  inverseOnSurface: Shade.green[4],
  inversePrimary: Shade.red[4],
  error: Shade.red[3],
  onError: Shade.green[1],
  shadow: Shade.orange[1],
  scrim: Shade.rose[1],
  outline: Shade.gray[3],
};

export { LightColors, DarkColors };
