import Shade from './shade';

const LightColors = {
  primary: Shade.primary[0],
  onPrimary: Shade.white[0],
  secondary: Shade.secondary[0],
  onSecondary: Shade.white[0],
  background: Shade.background[0],
  onBackground: Shade.text[0],
  surface: Shade.surface[0],
  onSurface: Shade.text[1],
  surfaceVariant: Shade.surface[1],
  onSurfaceVariant: Shade.text[3],
  primaryContainer: Shade.primary[1],
  onPrimaryContainer: Shade.primary[4],
  secondaryContainer: Shade.secondary[1],
  onSecondaryContainer: Shade.secondary[4],
  errorContainer: Shade.error[0],
  onErrorContainer: Shade.white[0],
  inverseSurface: Shade.surface[4],
  inverseOnSurface: Shade.text[4],
  inversePrimary: Shade.primary[4],
  error: Shade.error[3],
  onError: Shade.white[0],
  shadow: Shade.black[0],
  outline: Shade.border[2],
};

const DarkColors = {
  primary: Shade.primary[4],
  onPrimary: Shade.white[0],
  secondary: Shade.secondary[4],
  onSecondary: Shade.white[0],
  background: Shade.background[4],
  onBackground: Shade.text[4],
  surface: Shade.surface[4],
  onSurface: Shade.text[0],
  surfaceVariant: Shade.surface[3],
  onSurfaceVariant: Shade.text[1],
  primaryContainer: Shade.primary[3],
  onPrimaryContainer: Shade.primary[0],
  secondaryContainer: Shade.secondary[3],
  onSecondaryContainer: Shade.secondary[0],
  errorContainer: Shade.error[3],
  onErrorContainer: Shade.white[0],
  inverseSurface: Shade.surface[0],
  inverseOnSurface: Shade.text[1],
  inversePrimary: Shade.primary[0],
  error: Shade.error[1],
  onError: Shade.white[0],
  shadow: Shade.black[0],
  outline: Shade.border[3],
};

export { LightColors, DarkColors };
